/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo
 */
public class AlugarTela extends javax.swing.JFrame {

    private String[] temp;
    private String[] temp2;
    public String GRG;
    public String GPLACA;
    public String GTAXA;

    /**
     * Creates new form Alugar
     */
    public AlugarTela() {
        initComponents();

        lerClientes();
        lerVeiculos();
    }

    public void carregarCliente() {

        DefaultTableModel model = (DefaultTableModel) tabClientes.getModel();
        model.addRow(temp);

    }

    public void lerClientes() {
        try {
            InputStream is = new FileInputStream("clientes.txt");
            InputStreamReader isr = new InputStreamReader(is);
            BufferedReader br = new BufferedReader(isr);

            String b = br.readLine();

            while (b != null) {
                temp = new String[5];
                temp = b.split(";");

                carregarCliente();

                b = br.readLine();
            }
            br.close();
        } catch (Exception e) {
        }
    }

    public void carregarVeiculo() {

        DefaultTableModel model1 = (DefaultTableModel) tabVeiculos2.getModel();
        model1.addRow(temp2);

    }

    public void lerVeiculos() {
        try {
            InputStream nt = new FileInputStream("carros.txt");
            InputStreamReader nte = new InputStreamReader(nt);
            BufferedReader ue = new BufferedReader(nte);

            String c = ue.readLine();

            while (c != null) {
                temp2 = new String[7];
                temp2 = c.split(";");

                carregarVeiculo();

                c = ue.readLine();
            }
            ue.close();
        } catch (Exception e) {
        }
    }

    public void Alugar(String rg, String Placa, String Taxa, String horaAluguel, String dataAluguel) {
        File file = new File("Alugados.txt");
        try {
            int linha = tabVeiculos2.getSelectedRow();
            GPLACA = (tabVeiculos2.getValueAt(linha, 5)).toString();
            GTAXA = (tabVeiculos2.getValueAt(linha, 4)).toString();
            String marcaCarro = (tabVeiculos2.getValueAt(linha, 0)).toString();
            String modeloCarro = (tabVeiculos2.getValueAt(linha, 1)).toString();
            String corCarro = (tabVeiculos2.getValueAt(linha, 2)).toString();
            String categoriaCarro = (tabVeiculos2.getValueAt(linha, 3)).toString();

            FileWriter fileWriter = new FileWriter("Alugados.txt", true);
            BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
            bufferedWriter.write(GRG + ";" + GPLACA + ";" + GTAXA + ";" + horaAluguel + 
                    ";" + dataAluguel + ";" + marcaCarro + ";" + modeloCarro + ";" +
                    corCarro + ";" + categoriaCarro + ";");
            bufferedWriter.newLine();
            bufferedWriter.close();
        } catch (HeadlessException | IOException e) {
            System.out.println("Erro: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panAlugar = new javax.swing.JPanel();
        tabAlugar = new javax.swing.JTabbedPane();
        panSelCliente = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabClientes = new javax.swing.JTable();
        proximaTela = new javax.swing.JButton();
        btnSairAlugar = new javax.swing.JButton();
        panSelVeiculo = new javax.swing.JPanel();
        tabVeiculos = new javax.swing.JScrollPane();
        tabVeiculos2 = new javax.swing.JTable();
        finalizar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aluguel de Veículo");

        tabAlugar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabAlugar.setEnabled(false);

        tabClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "RG", "CPF", "CNH", "Fone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabClientes);
        if (tabClientes.getColumnModel().getColumnCount() > 0) {
            tabClientes.getColumnModel().getColumn(3).setResizable(false);
        }

        proximaTela.setText("Próximo Passo");
        proximaTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximaTelaActionPerformed(evt);
            }
        });

        btnSairAlugar.setText("Sair");
        btnSairAlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairAlugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panSelClienteLayout = new javax.swing.GroupLayout(panSelCliente);
        panSelCliente.setLayout(panSelClienteLayout);
        panSelClienteLayout.setHorizontalGroup(
            panSelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSelClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(proximaTela, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210)
                .addComponent(btnSairAlugar)
                .addGap(25, 25, 25))
        );
        panSelClienteLayout.setVerticalGroup(
            panSelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panSelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proximaTela, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSairAlugar)))
        );

        tabAlugar.addTab("Seleção de Cliente", panSelCliente);

        tabVeiculos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Cor", "Categoria", "Taxa", "Placa", "Disponivel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabVeiculos.setViewportView(tabVeiculos2);

        finalizar.setActionCommand("Finalizar Locação");
        finalizar.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        finalizar.setLabel("Finalizar Locação");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panSelVeiculoLayout = new javax.swing.GroupLayout(panSelVeiculo);
        panSelVeiculo.setLayout(panSelVeiculoLayout);
        panSelVeiculoLayout.setHorizontalGroup(
            panSelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSelVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSelVeiculoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(262, 262, 262))
                    .addComponent(tabVeiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
                .addContainerGap())
        );
        panSelVeiculoLayout.setVerticalGroup(
            panSelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSelVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        finalizar.getAccessibleContext().setAccessibleName("Finalizar");

        tabAlugar.addTab("Seleção de Veículo", panSelVeiculo);

        javax.swing.GroupLayout panAlugarLayout = new javax.swing.GroupLayout(panAlugar);
        panAlugar.setLayout(panAlugarLayout);
        panAlugarLayout.setHorizontalGroup(
            panAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabAlugar)
        );
        panAlugarLayout.setVerticalGroup(
            panAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabAlugar)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panAlugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panAlugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(716, 398));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairAlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairAlugarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairAlugarActionPerformed

    private void proximaTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximaTelaActionPerformed

        tabAlugar.setSelectedIndex(1);
        int linha = tabClientes.getSelectedRow();
        GRG = (tabClientes.getValueAt(linha, 1)).toString();
        System.out.println(GRG);

    }//GEN-LAST:event_proximaTelaActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed

        int linha = tabVeiculos2.getSelectedRow();

        if (tabVeiculos2.getValueAt(linha, 6).equals("S")) {

            GPLACA = (tabVeiculos2.getValueAt(linha, 5)).toString();
            GTAXA = (tabVeiculos2.getValueAt(linha, 4)).toString();
            String marcaCarro = (tabVeiculos2.getValueAt(linha, 0)).toString();
            String modeloCarro = (tabVeiculos2.getValueAt(linha, 1)).toString();
            String corCarro = (tabVeiculos2.getValueAt(linha, 2)).toString();
            String categoriaCarro = (tabVeiculos2.getValueAt(linha, 3)).toString();

            tabVeiculos2.setValueAt("N", linha, 6);

            System.out.println(GPLACA);

            Date datasistema = new Date();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            System.out.println((formato.format(datasistema)));

            Calendar now = Calendar.getInstance();
            System.out.println((String.format("%1$tH:%1$tM:%1$tS", now)));

            String horaAluguel = String.format("%1$tH:%1$tM:%1$tS", now);
            String dataAluguel = formato.format(datasistema);

            Alugar(GRG, GPLACA, GTAXA, horaAluguel, dataAluguel);

            JOptionPane.showMessageDialog(null, "Locação Realizada com sucesso!");
            this.dispose();

            //////
            //início
            //Procura a linha em que a placa está cadastrada e reescreve ela
            String oldFileName = "carros.txt";
            String tmpFileName = "tmp_carros.txt";

            BufferedReader br = null;
            BufferedWriter bw = null;

            try {
                br = new BufferedReader(new FileReader(oldFileName));
                bw = new BufferedWriter(new FileWriter(tmpFileName));
                String line;
                while ((line = br.readLine()) != null) {
                    if (line.contains(GPLACA)) {
                        line = line.replaceAll(line, (marcaCarro + ";" + modeloCarro +
                                ";" + corCarro + ";" + categoriaCarro + ";" + GTAXA +
                                ";" + GPLACA + ";" + "N"));
                    }
                    bw.write(line + "\n");
                }
            } catch (Exception e) {
                return;
            } finally {
                try {
                    if (br != null) {
                        br.close();
                    }
                } catch (IOException e) {
                    //
                }
                try {
                    if (bw != null) {
                        bw.close();
                    }
                } catch (IOException e) {
                    //
                }
            }
            //deleta o arquivo antigo
            File oldFile = new File(oldFileName);
            oldFile.delete();

            //Renomeia o arquivo temporário
            File newFile = new File(tmpFileName);
            newFile.renameTo(oldFile);

            //fim
            //////
        } else {
            JOptionPane.showMessageDialog(null, "Veículo encontra-se indisponível!");
        }

    }//GEN-LAST:event_finalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlugarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlugarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlugarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlugarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlugarTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSairAlugar;
    private java.awt.Button finalizar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panAlugar;
    private javax.swing.JPanel panSelCliente;
    private javax.swing.JPanel panSelVeiculo;
    private javax.swing.JButton proximaTela;
    private javax.swing.JTabbedPane tabAlugar;
    private javax.swing.JTable tabClientes;
    private javax.swing.JScrollPane tabVeiculos;
    private javax.swing.JTable tabVeiculos2;
    // End of variables declaration//GEN-END:variables
}
