/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora;

import java.awt.HeadlessException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class ClienteTela extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    private Cliente[] clientes = new Cliente[1000];
    private int qtd = 0;

    public ClienteTela() {
        initComponents();
    }

    public void persistir() {
        File file = new File("clientes.txt");

        for (int i = 0; i < qtd; i++) {
            try {

                Cliente nclientes = clientes[i];

                //verifica se o arquivo já existe e escreve no final do mesmo
                FileWriter fileWriter = new FileWriter("clientes.txt", true);
                BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);

                bufferedWriter.write(nclientes.getNome() + ";" + nclientes.getRg()
                        + ";" + nclientes.getCpf() + ";" + nclientes.getCnh() + ";"
                        + nclientes.getFone() + ";");
                bufferedWriter.newLine();
                bufferedWriter.close();

            } catch (HeadlessException | IOException e) {
                System.out.println("Erro: " + e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdskCliente = new javax.swing.JDesktopPane();
        btnSairCliente = new javax.swing.JButton();
        lblNomeCliente = new javax.swing.JLabel();
        lblRgCliente = new javax.swing.JLabel();
        jscrTxtNomeCliente = new javax.swing.JScrollPane();
        txtNomeCliente = new javax.swing.JTextPane();
        jscrTxtRgCliente = new javax.swing.JScrollPane();
        txtRgCliente = new javax.swing.JTextPane();
        btnCadastrarCliente = new javax.swing.JButton();
        lblCpfCliente = new javax.swing.JLabel();
        lblCnhCliente = new javax.swing.JLabel();
        lblFoneCliente = new javax.swing.JLabel();
        jscrTxtCpfCliente = new javax.swing.JScrollPane();
        txtCpfCliente = new javax.swing.JTextPane();
        jscrCnhCliente = new javax.swing.JScrollPane();
        txtCnhCliente = new javax.swing.JTextPane();
        jscrFoneCliente = new javax.swing.JScrollPane();
        txtFoneCliente = new javax.swing.JTextPane();
        btnLimparCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jdskCliente.setBackground(new java.awt.Color(153, 153, 153));

        btnSairCliente.setText("Finalizar Cadastro");
        btnSairCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairClienteActionPerformed(evt);
            }
        });

        lblNomeCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeCliente.setText("Nome:");

        lblRgCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblRgCliente.setText("RG:");

        jscrTxtNomeCliente.setViewportView(txtNomeCliente);

        jscrTxtRgCliente.setViewportView(txtRgCliente);

        btnCadastrarCliente.setText("Cadastrar");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        lblCpfCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCpfCliente.setText("CPF:");

        lblCnhCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCnhCliente.setText("CNH:");

        lblFoneCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblFoneCliente.setText("Fone:");

        jscrTxtCpfCliente.setViewportView(txtCpfCliente);

        jscrCnhCliente.setViewportView(txtCnhCliente);

        jscrFoneCliente.setViewportView(txtFoneCliente);

        btnLimparCliente.setText("Limpar");
        btnLimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparClienteActionPerformed(evt);
            }
        });

        jdskCliente.setLayer(btnSairCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCliente.setLayer(lblNomeCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCliente.setLayer(lblRgCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCliente.setLayer(jscrTxtNomeCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCliente.setLayer(jscrTxtRgCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCliente.setLayer(btnCadastrarCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCliente.setLayer(lblCpfCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCliente.setLayer(lblCnhCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCliente.setLayer(lblFoneCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCliente.setLayer(jscrTxtCpfCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCliente.setLayer(jscrCnhCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCliente.setLayer(jscrFoneCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCliente.setLayer(btnLimparCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdskClienteLayout = new javax.swing.GroupLayout(jdskCliente);
        jdskCliente.setLayout(jdskClienteLayout);
        jdskClienteLayout.setHorizontalGroup(
            jdskClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdskClienteLayout.createSequentialGroup()
                .addGroup(jdskClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jdskClienteLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jscrTxtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdskClienteLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblCnhCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jscrCnhCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdskClienteLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblFoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jscrFoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdskClienteLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnCadastrarCliente)
                        .addGap(29, 29, 29)
                        .addComponent(btnLimparCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSairCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdskClienteLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jdskClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRgCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeCliente))
                        .addGap(18, 18, 18)
                        .addGroup(jdskClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jscrTxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jscrTxtRgCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        jdskClienteLayout.setVerticalGroup(
            jdskClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdskClienteLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jdskClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jscrTxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdskClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRgCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jscrTxtRgCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdskClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jscrTxtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdskClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCnhCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jscrCnhCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdskClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jscrFoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jdskClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdskClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrarCliente))
                    .addGroup(jdskClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparCliente))
                    .addGroup(jdskClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSairCliente))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdskCliente)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdskCliente)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairClienteActionPerformed
        //fecha a janela Cliente
        persistir();
        this.dispose();
    }//GEN-LAST:event_btnSairClienteActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        //recebe os dados do cliente

        String nomeCliente = txtNomeCliente.getText();
        String rgCliente = txtRgCliente.getText();
        String cpfCliente = txtCpfCliente.getText();
        String cnhCliente = txtCnhCliente.getText();
        String foneCliente = txtFoneCliente.getText();

        Cliente nclientes = new Cliente(nomeCliente, rgCliente, cpfCliente, cnhCliente,
                foneCliente);

        clientes[qtd] = nclientes;
        qtd++;

        JOptionPane.showMessageDialog(null, "Cliente cadastrado!");

        //apaga dados
        txtNomeCliente.setText("");
        txtRgCliente.setText("");
        txtCpfCliente.setText("");
        txtCnhCliente.setText("");
        txtFoneCliente.setText("");

    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnLimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparClienteActionPerformed
        txtNomeCliente.setText("");
        txtRgCliente.setText("");
        txtCpfCliente.setText("");
        txtCnhCliente.setText("");
        txtFoneCliente.setText("");
    }//GEN-LAST:event_btnLimparClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnLimparCliente;
    private javax.swing.JButton btnSairCliente;
    private javax.swing.JDesktopPane jdskCliente;
    private javax.swing.JScrollPane jscrCnhCliente;
    private javax.swing.JScrollPane jscrFoneCliente;
    private javax.swing.JScrollPane jscrTxtCpfCliente;
    private javax.swing.JScrollPane jscrTxtNomeCliente;
    private javax.swing.JScrollPane jscrTxtRgCliente;
    private javax.swing.JLabel lblCnhCliente;
    private javax.swing.JLabel lblCpfCliente;
    private javax.swing.JLabel lblFoneCliente;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblRgCliente;
    private javax.swing.JTextPane txtCnhCliente;
    private javax.swing.JTextPane txtCpfCliente;
    private javax.swing.JTextPane txtFoneCliente;
    private javax.swing.JTextPane txtNomeCliente;
    private javax.swing.JTextPane txtRgCliente;
    // End of variables declaration//GEN-END:variables
}
