/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora;

import java.awt.HeadlessException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class VeiculoTela extends javax.swing.JFrame {

    private Veiculo[] carros = new Veiculo[1000];
    private int qtd = 0;

    /**
     * Creates new form Carro
     */
    public VeiculoTela() {
        initComponents();
    }

    public void persistir() {
        File file = new File("carros.txt");

        for (int i = 0; i < qtd; i++) {
            try {

                Veiculo carro = carros[i];

                //verifica se o arquivo já existe e escreve no final do mesmo
                FileWriter fileWriter = new FileWriter("carros.txt", true);
                BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);

                bufferedWriter.write(carro.getMarca() + ";" + carro.getModelo() + ";" + carro.getCor() + ";" + carro.getCategoria() + ";" + carro.getTaxa() + ";" + carro.getPlaca() + ";" + carro.getDisponivel() + ";");
                bufferedWriter.newLine();
                bufferedWriter.close();

            } catch (HeadlessException | IOException e) {
                System.out.println("Erro: " + e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdskCarro = new javax.swing.JDesktopPane();
        btnSairCarro = new javax.swing.JButton();
        lblModeloCarro = new javax.swing.JLabel();
        lblPlacaCarro = new javax.swing.JLabel();
        jscrTxtModeloCarro = new javax.swing.JScrollPane();
        txtModeloCarro = new javax.swing.JTextPane();
        jscrTxtPlacaCarro = new javax.swing.JScrollPane();
        txtPlacaCarro = new javax.swing.JTextPane();
        btnCadastrarCarro = new javax.swing.JToggleButton();
        lblMarcaCarro = new javax.swing.JLabel();
        jscrMarcaCarro = new javax.swing.JScrollPane();
        txtMarcaCarro = new javax.swing.JTextPane();
        lblCorCarro = new javax.swing.JLabel();
        jscrCorCarro = new javax.swing.JScrollPane();
        txtCorCarro = new javax.swing.JTextPane();
        lblAnoCarro = new javax.swing.JLabel();
        jscrAnoCarro = new javax.swing.JScrollPane();
        txtTaxaCarro = new javax.swing.JTextPane();
        lblCategoriaCarro = new javax.swing.JLabel();
        cboxCategoriaCarro = new javax.swing.JComboBox<>();
        btnLimparCarro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Veículo");

        jdskCarro.setBackground(new java.awt.Color(153, 153, 153));

        btnSairCarro.setText("Finalizar Cadastro");
        btnSairCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCarroActionPerformed(evt);
            }
        });

        lblModeloCarro.setBackground(new java.awt.Color(204, 204, 204));
        lblModeloCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblModeloCarro.setText("Modelo");

        lblPlacaCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacaCarro.setText("Placa");

        jscrTxtModeloCarro.setViewportView(txtModeloCarro);

        jscrTxtPlacaCarro.setViewportView(txtPlacaCarro);

        btnCadastrarCarro.setText("Cadastrar");
        btnCadastrarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCarroActionPerformed(evt);
            }
        });

        lblMarcaCarro.setBackground(new java.awt.Color(204, 204, 204));
        lblMarcaCarro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMarcaCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblMarcaCarro.setText("Marca");

        jscrMarcaCarro.setViewportView(txtMarcaCarro);

        lblCorCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblCorCarro.setText("Cor");

        jscrCorCarro.setViewportView(txtCorCarro);

        lblAnoCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblAnoCarro.setText("Diária");

        jscrAnoCarro.setViewportView(txtTaxaCarro);

        lblCategoriaCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoriaCarro.setText("Categoria");

        cboxCategoriaCarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Esportivo", "Sedã", "Popular", "Moto" }));

        btnLimparCarro.setText("Limpar");
        btnLimparCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCarroActionPerformed(evt);
            }
        });

        jdskCarro.setLayer(btnSairCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCarro.setLayer(lblModeloCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCarro.setLayer(lblPlacaCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCarro.setLayer(jscrTxtModeloCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCarro.setLayer(jscrTxtPlacaCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCarro.setLayer(btnCadastrarCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCarro.setLayer(lblMarcaCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCarro.setLayer(jscrMarcaCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCarro.setLayer(lblCorCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCarro.setLayer(jscrCorCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCarro.setLayer(lblAnoCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCarro.setLayer(jscrAnoCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCarro.setLayer(lblCategoriaCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCarro.setLayer(cboxCategoriaCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdskCarro.setLayer(btnLimparCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdskCarroLayout = new javax.swing.GroupLayout(jdskCarro);
        jdskCarro.setLayout(jdskCarroLayout);
        jdskCarroLayout.setHorizontalGroup(
            jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdskCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblCorCarro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblModeloCarro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addComponent(lblAnoCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblMarcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdskCarroLayout.createSequentialGroup()
                        .addGroup(jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jscrMarcaCarro)
                            .addComponent(jscrTxtModeloCarro)
                            .addGroup(jdskCarroLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSairCarro)
                                .addGap(13, 13, 13))
                            .addGroup(jdskCarroLayout.createSequentialGroup()
                                .addGroup(jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jscrCorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jdskCarroLayout.createSequentialGroup()
                                        .addGroup(jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jscrAnoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jdskCarroLayout.createSequentialGroup()
                                                .addGap(145, 145, 145)
                                                .addComponent(lblPlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(32, 32, 32)
                                        .addComponent(jscrTxtPlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jdskCarroLayout.createSequentialGroup()
                        .addGroup(jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCategoriaCarro)
                            .addGroup(jdskCarroLayout.createSequentialGroup()
                                .addComponent(btnCadastrarCarro)
                                .addGap(34, 34, 34)
                                .addComponent(btnLimparCarro)
                                .addGap(14, 14, 14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(cboxCategoriaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        jdskCarroLayout.setVerticalGroup(
            jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdskCarroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMarcaCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jscrMarcaCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jscrTxtModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCategoriaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboxCategoriaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jscrCorCarro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(lblCorCarro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jscrTxtPlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jscrAnoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jdskCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSairCarro)
                    .addComponent(btnLimparCarro)
                    .addComponent(btnCadastrarCarro))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdskCarro)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdskCarro)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCarroActionPerformed

        persistir();
        //fecha janela Carro
        this.dispose();
    }//GEN-LAST:event_btnSairCarroActionPerformed

    private void btnCadastrarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCarroActionPerformed

        //atribui as informações às variáveis
        String modeloCarro = txtModeloCarro.getText();
        String marcaCarro = txtMarcaCarro.getText();
        String corCarro = txtCorCarro.getText();
        Object selectedItem = cboxCategoriaCarro.getSelectedItem();
        String categoriaCarro = selectedItem.toString();
        String taxaCarro = txtTaxaCarro.getText();
        String placaCarro = txtPlacaCarro.getText();

        //Criar um objeto Carro
        Veiculo carro = new Veiculo(marcaCarro, modeloCarro, corCarro, categoriaCarro, taxaCarro, placaCarro, "S");

        //Adicionando ao vetor
        carros[qtd] = carro;
        qtd++;

        //confirmação de cadastro
        JOptionPane.showMessageDialog(null, "Carro cadastrado!");

        txtModeloCarro.setText("");
        txtMarcaCarro.setText("");
        txtCorCarro.setText("");
        txtTaxaCarro.setText("");
        txtPlacaCarro.setText("");


    }//GEN-LAST:event_btnCadastrarCarroActionPerformed

    private void btnLimparCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCarroActionPerformed
        txtModeloCarro.setText("");
        txtMarcaCarro.setText("");
        txtCorCarro.setText("");
        txtTaxaCarro.setText("");
        txtPlacaCarro.setText("");
    }//GEN-LAST:event_btnLimparCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeiculoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeiculoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeiculoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeiculoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeiculoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCadastrarCarro;
    private javax.swing.JButton btnLimparCarro;
    private javax.swing.JButton btnSairCarro;
    private javax.swing.JComboBox<String> cboxCategoriaCarro;
    private javax.swing.JDesktopPane jdskCarro;
    private javax.swing.JScrollPane jscrAnoCarro;
    private javax.swing.JScrollPane jscrCorCarro;
    private javax.swing.JScrollPane jscrMarcaCarro;
    private javax.swing.JScrollPane jscrTxtModeloCarro;
    private javax.swing.JScrollPane jscrTxtPlacaCarro;
    private javax.swing.JLabel lblAnoCarro;
    private javax.swing.JLabel lblCategoriaCarro;
    private javax.swing.JLabel lblCorCarro;
    private javax.swing.JLabel lblMarcaCarro;
    private javax.swing.JLabel lblModeloCarro;
    private javax.swing.JLabel lblPlacaCarro;
    private javax.swing.JTextPane txtCorCarro;
    private javax.swing.JTextPane txtMarcaCarro;
    private javax.swing.JTextPane txtModeloCarro;
    private javax.swing.JTextPane txtPlacaCarro;
    private javax.swing.JTextPane txtTaxaCarro;
    // End of variables declaration//GEN-END:variables
}
